# ========================================
# DATABASE
# ========================================

spring.datasource.url=jdbc:h2:mem:bedroom_test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ========================================
# JPA
# ========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ========================================
# FLYWAY
# ========================================

spring.flyway.enabled=true

# ========================================
# JWT
# ========================================

bedroom.security.jwt.public-key=${BEDROOM_JWT_PUBLIC_KEY}
bedroom.security.jwt.private-key=${BEDROOM_JWT_PRIVATE_KEY}