# ========================================
# DATABASE
# ========================================

spring.datasource.url=jdbc:mysql://localhost:3306/bedroom_dev
spring.datasource.username=root
spring.datasource.password=

# ========================================
# JPA
# ========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

bedroom.security.jwt.public-key=${BEDROOM_JWT_PUBLIC_KEY}
bedroom.security.jwt.private-key=${BEDROOM_JWT_PRIVATE_KEY}